print("one Sunny day in a park there was a person named " + input("What is your name?: "))
print("and they were " + input("enter a verb (ending in ING): "))
print("When suddenly right from a bush a " + input("enter a noun(animal:"))
print("it was so " + input("enter a adjective:"))
print("but they were scared by the sudden apprence of it they " + input("enter a verb(past tense):"))
print("untill it began to rain so to get away from it they hid in a " + input("enter a noun(place):"))
print("as soon as they caught their breath they saw a  " + input("enter a noun (a bug that would scare you:"))
print("and it was so " + input("enter a adjective:"))
print("so they had to " + input("enter a verb(present):"))
print("until the saftely reached home")
